// Generated by Wrangler by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
	ALLOWED_DOMAINS: ["yellowdumpsterservice.com"] | ["localhost"];
	MASK_DOMAIN: "https://www.rentyellowdumpsters.com";
	ENVIRONMENT: "production" | "development";
}
